### ISSUE TITLE
How to use these layers?

### ISSUE THREAD

**Issue by 9thDimension** [WeidiXie/New_Layers-Keras-Tensorflow#1]
Very excited to see these operations implemented from cutting edge papers - I have tried and failed to create the Correlation Layer from DeepMatching [1], Trainable DeepMatching [2], Geometric Matching [3], Fully Convolutional Siamese Tracking [4] etc.

Having cloned this repo, I'm failing to see how I can use the `Normalized_Correlation_Layer`. It extends `Layer` but invokes a sueprclass constructor `Correlation_Layer` [here](https://github.com/WeidiXie/New_Layers-Keras-Tensorflow/blob/master/src/normalized_correlation_layer.py#L65). This `Correlation_Layer` class is nowhere to be found, so I get this error:

```
/home/hal9000/keras122env/bin/python /home/hal9000/Sources/New_Layers-Keras-Tensorflow/test/test_normalized_correlation_layer.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/hal9000/Sources/New_Layers-Keras-Tensorflow/test/test_normalized_correlation_layer.py", line 59, in <module>
    model = BuildModel(dim=(height, width, 3))
  File "/home/hal9000/Sources/New_Layers-Keras-Tensorflow/test/test_normalized_correlation_layer.py", line 42, in BuildModel
    y_corr = Normalized_Correlation_Layer(patch_size=patch_size, stride=stride)([input_a, input_a])
  File "/home/hal9000/Sources/New_Layers-Keras-Tensorflow/test/normalized_correlation_layer.py", line 65, in __init__
    super(Correlation_Layer, self).__init__(**kwargs)
NameError: global name 'Correlation_Layer' is not defined
```

[1] https://arxiv.org/abs/1506.07656
[2] http://www.robots.ox.ac.uk/~tvg/publications/2016/FullyTrainableDeepMatching.pdf
[3] https://arxiv.org/abs/1703.05593
[4] https://arxiv.org/abs/1606.09549

**Comment by lc82111** [comment]
In python, the super keyword just invokes the base class, the layer calss, in this case. So, I think 
`super(Correlation_Layer, self).__init__(**kwargs) ` shoud be `super(Normalized_Correlation_Layer , self).__init__(**kwargs)`

**Comment by lc82111** [comment]
what I am curious about is the  param patch_size that does not appear in the content of the paper itself.

**Comment by WeidiXie** [comment]
Sorry guys,
I haven't maintained this repo for a very long time, 
I guess you are right, it was a typo

also, I think some tensorflow may have updated several new functions, making this implementation much easier.

**Comment by WeidiXie** [comment]
@lc82111  Regarding to your question, 
it is true that the paper does not have this patch_size, but it is really a parameter that you can adjust, to play with the receptive field.

**Comment by lc82111** [comment]
@WeidiXie thanks for reply. I also note that the channel-wise normalization of the correlation map is replaced with mean removal and variance scaling. May I ask why?

**Comment by 9thDimension** [comment]
> also, I think some tensorflow may have updated several new functions, making this implementation much easier.

What functions are those? Is im_2_col relevant? 

Can you think of a way of implementing the repeated dot products with a convolution layer? I think the default convolutional layer wants the filter tensors to be the same trainable parameters over the course of learning, whereas in this case we want the "filters" to be little squares of image/feature tensor that naturally change on every different pair of inputs.
